{
 "title": "System & Kafka dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hosts", "query": "label_values(host)" }
  ]
 },
 "panels": [
  { "title": "Connect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incomming Byte Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_incoming_byte_rate",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Outgoing byte rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_outgoing_byte_rate",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Kafka producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg",
     "legendFormat": "({{ instance }}) latency avg"
    },
    {
     "expr": "kafka_producer_request_latency_max",
     "legendFormat": "({{ instance }}) latency max"
    }
   ]
  },
  {
   "title": "Request & response rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "kafka_producer_request_rate", "legendFormat": "({{ instance }}) request" },
    { "expr": "kafka_producer_response_rate", "legendFormat": "({{ instance }}) response" }
   ]
  },
  { "title": "Kafka consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Records lag max",
   "type": "graph",
   "description": "The maximum lag in terms of number of records for any partition in this window. An increasing value over time is your best indication that the consumer group is not keeping up with the producers.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_consumer_records_lag_max", "legendFormat": "({{ instance }}) lag max" }
   ]
  },
  {
   "title": "Average  bytes consumed per second.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_bytes_consumed_rate",
     "legendFormat": "({{ instance }}) bytes rate"
    }
   ]
  },
  {
   "title": "Average  records consumed per second.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_consumed_rate",
     "legendFormat": "({{ instance }}) records rate"
    }
   ]
  },
  {
   "title": "Fetch requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "kafka_consumer_fetch_rate", "legendFormat": "({{ instance }}) fetch rate" }
   ]
  },
  {
   "title": "Time for a fetch request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_latency_avg",
     "legendFormat": "({{ instance }}) latency avg"
    },
    {
     "expr": "kafka_consumer_fetch_latency_max",
     "legendFormat": "({{ instance }}) latency max"
    }
   ]
  },
  {
   "title": "Average throttle time",
   "type": "graph",
   "description": "When quotas are enabled, the broker may delay fetch requests in order to throttle a consumer which has exceeded its limit. This metric indicates how throttling time has been added to fetch requests on average.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_throttle_time_avg",
     "legendFormat": "({{ instance }}) throttle time avg"
    },
    {
     "expr": "kafka_consumer_fetch_throttle_time_max",
     "legendFormat": "({{ instance }}) throttle time  max"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_connection_count",
     "legendFormat": "({{ instance }}) connections"
    }
   ]
  },
  {
   "title": "New established connections rate",
   "type": "graph",
   "description": "New connections established per second in the window.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_connection_creation_rate",
     "legendFormat": "({{ instance }}) connection rate"
    }
   ]
  }
 ]
}